version: '3'
services:
  app:
    build: .
    command: tail -F anything
    volumes:
      - data:/app
      - ./target:/app/dist/target
      - ./src/main/resources:/app/dist/config
      - ./tmp:/app/dist/tmp
volumes:
  data:
